In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
sbn.set()

In [3]:
from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [4]:
df1 = pd.read_table('../combined/shtmax01.txt', sep='\s+',header=None,index_col=0)
#df1
maxS1 = df1.stack()
#print(maxS1.index)
#for year_day in maxS1.index:
   # print(year_day)
datesMax1=[]
for y in range(1893,2014):
    for d in range(1,32):
        time = "1"+"-"+str(d)+"-"+str(y)
        datesMax1.append(time)
#(datesMax1)

dateMax1 = pd.Series(pd.to_datetime(date) for date in datesMax1)
#dateMax1
#(maxS1.values)
df1 = pd.DataFrame(data=maxS1.values,index=dateMax1)
df1.columns = ['Max']
df1
        
        

#type(maxS1)
#idx=maxS1.index
#year = idx.get_level_values(0);
#days = idx.get_level_values(1);
#dates=[]
#dash = "-"
#month = "1"
#year
#for y in year:
    #print(y)
    #for d in days:
       # print(y,d)
        #time = month+dash+str(d)+dash+str(year)
        #dates.append(time)
#dates
        

#maxS1.values
#date = pd.date_range('1/1/1893','2/19/1893',freq='M')
#date


#df2 = pd.read_table('../combined/shtmax02.txt', sep='\s+',header=None,index_col=0)
#unM1 = maxS1.to_frame(name="max")

            Max
1893-01-01  -99
1893-01-02  -99
1893-01-03  -99
1893-01-04  -99
1893-01-05  -99
1893-01-06  -99
1893-01-07  -99
1893-01-08  -99
1893-01-09  -99
1893-01-10  -99
1893-01-11  -99
1893-01-12  -99
1893-01-13  -99
1893-01-14  -99
1893-01-15  -99
1893-01-16  -99
1893-01-17  -99
1893-01-18  -99
1893-01-19  -99
1893-01-20  -99
1893-01-21  -99
1893-01-22  -99
1893-01-23  -99
1893-01-24  -99
1893-01-25  -99
1893-01-26  -99
1893-01-27  -99
1893-01-28  -99
1893-01-29  -99
1893-01-30  -99
...         ...
2013-01-02   20
2013-01-03   25
2013-01-04   29
2013-01-05   33
2013-01-06   33
2013-01-07   38
2013-01-08   40
2013-01-09   38
2013-01-10   41
2013-01-11   42
2013-01-12   48
2013-01-13   19
2013-01-14   26
2013-01-15   33
2013-01-16   41
2013-01-17   38
2013-01-18   48
2013-01-19   47
2013-01-20   43
2013-01-21   15
2013-01-22    8
2013-01-23   20
2013-01-24   17
2013-01-25   25
2013-01-26   23
2013-01-27   31
2013-01-28   33
2013-01-29   48
2013-01-30   35
2013-01-31   19

[3751 rows x 1 columns]

In [5]:
dfMin1 = pd.read_table('../combined/shtmin01.txt', sep='\s+',header=None,index_col=0)
minS1 = dfMin1.stack()
dfPre1 = pd.read_table('../combined/shtpre01.txt', sep='\s+',header=None,index_col=0)
precipS1 = dfPre1.stack()
dfSno1 = pd.read_table('../combined/shtsno_b01.txt', sep='\s+',header=None,index_col=0)
snowS1 = dfSno1.stack()
df1['Min']=minS1.values
df1['Precip']=precipS1.values
df1['Snow']=snowS1.values
df1

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-01-02   20    0       0     0
2013-01-03   25   13       0     0
2013-01-04   29    4       0     0
2013-01-05   33    3       0     0
2013-01-06   33   12       0     0
2013-01-07   38    5       0     0
2013-01-08   40    8       0     0
2013-01-09   38   25       0     0
2013-01-10   41   14       0     0
2013-01-11   42   33      19     0
2013-01-12   48   19       0     0
2013-01-13   19    7       0     0
2013-01-14   26    4       0     0
2013-01-15   33    7       0     0
2013-01-16   41   20       0     0
2013-01-17   38   11       0     0
2013-01-18   48   15       0     0
2013-01-19   47   27       0     0
2013-01-20   43    3       0     0
2013-01-21   15   -7       0     0
2013-01-22    8   -8       0     0
2013-01-23   20    4       3     2
2013-01-24   17   -3       0     0
2013-01-25   25   11       0     0
2013-01-26   23    0       0     0
2013-01-27   31   23      31     0
2013-01-28   33   31       0     0
2013-01-29   48   32       0     0
2013-01-30   35   19      28     4
2013-01-31   19    2       1     0

[3751 rows x 4 columns]

In [6]:
df2 = pd.read_table('../combined/shtmax02.txt', sep='\s+',header=None,index_col=0)
maxS2 = df2.stack()
datesMax2=[]
for y in range(1893,2014):
    for d in range(1,29):
        time = "2"+"-"+str(d)+"-"+str(y)
        datesMax2.append(time)
dateMax2 = pd.Series(pd.to_datetime(date) for date in datesMax2)
#dateMax2
        
df2 = pd.DataFrame(data=maxS2.values,index=dateMax2)
df2.columns = ['Max']
dfMin2 = pd.read_table('../combined/shtmin02.txt', sep='\s+',header=None,index_col=0)
minS2 = dfMin2.stack()
dfPre2 = pd.read_table('../combined/shtpre02.txt', sep='\s+',header=None,index_col=0)
precipS2 = dfPre2.stack()
dfSno2 = pd.read_table('../combined/shtsno_b02.txt', sep='\s+',header=None,index_col=0)
snowS2 = dfSno2.stack()
df2['Min']=minS2.values
df2['Precip']=precipS2.values
df2['Snow']=snowS2.values
df2

            Max  Min  Precip  Snow
1893-02-01  -99  -99   -9900     0
1893-02-02  -99  -99   -9900     0
1893-02-03  -99  -99   -9900     0
1893-02-04  -99  -99   -9900     0
1893-02-05  -99  -99   -9900     0
1893-02-06  -99  -99   -9900     0
1893-02-07  -99  -99   -9900     0
1893-02-08  -99  -99   -9900     0
1893-02-09  -99  -99   -9900     0
1893-02-10  -99  -99   -9900     0
1893-02-11  -99  -99   -9900     0
1893-02-12  -99  -99   -9900     0
1893-02-13  -99  -99   -9900     0
1893-02-14  -99  -99   -9900     0
1893-02-15  -99  -99   -9900     0
1893-02-16  -99  -99   -9900     0
1893-02-17  -99  -99   -9900     0
1893-02-18  -99  -99   -9900     0
1893-02-19  -99  -99   -9900     0
1893-02-20  -99  -99   -9900     0
1893-02-21  -99  -99   -9900     0
1893-02-22  -99  -99   -9900     0
1893-02-23  -99  -99   -9900     0
1893-02-24  -99  -99   -9900     0
1893-02-25  -99  -99   -9900     0
1893-02-26  -99  -99   -9900     0
1893-02-27  -99  -99   -9900     0
1893-02-28  -99  -99   -9900     0
1894-02-01   18   -6       0     0
1894-02-02   23    5       0     0
...         ...  ...     ...   ...
2012-02-27   46   22       0     0
2012-02-28   35   19      82     0
2013-02-01    5  -13       0     0
2013-02-02   15    2       7     1
2013-02-03   18    7       3     1
2013-02-04   20   13      20     2
2013-02-05   32    5       5     1
2013-02-06   32   -1       0     0
2013-02-07   35   30       8     0
2013-02-08   30   25       0     0
2013-02-09   29   16       0     0
2013-02-10   37   28      39     0
2013-02-11   37   26      18     1
2013-02-12   35   17       0     0
2013-02-13   35   14       0     0
2013-02-14   37   31       1     0
2013-02-15   34   13       0     0
2013-02-16   22    6       0     0
2013-02-17   31    6       0     0
2013-02-18   39   22       0     0
2013-02-19   28    3       1     0
2013-02-20   21   -1       0     0
2013-02-21   22    4       0     0
2013-02-22   30   21      32     4
2013-02-23   27   17       0     0
2013-02-24   34   -2       0     0
2013-02-25   41   23       0     0
2013-02-26   40   21       0     0
2013-02-27   35   28      14     3
2013-02-28   33   28       0     0

[3388 rows x 4 columns]

In [7]:
#result = pd.concat([df1,df2],axis=1)
result1 = df1.combine_first(df2)
result1

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-01-30   35   19      28     4
2013-01-31   19    2       1     0
2013-02-01    5  -13       0     0
2013-02-02   15    2       7     1
2013-02-03   18    7       3     1
2013-02-04   20   13      20     2
2013-02-05   32    5       5     1
2013-02-06   32   -1       0     0
2013-02-07   35   30       8     0
2013-02-08   30   25       0     0
2013-02-09   29   16       0     0
2013-02-10   37   28      39     0
2013-02-11   37   26      18     1
2013-02-12   35   17       0     0
2013-02-13   35   14       0     0
2013-02-14   37   31       1     0
2013-02-15   34   13       0     0
2013-02-16   22    6       0     0
2013-02-17   31    6       0     0
2013-02-18   39   22       0     0
2013-02-19   28    3       1     0
2013-02-20   21   -1       0     0
2013-02-21   22    4       0     0
2013-02-22   30   21      32     4
2013-02-23   27   17       0     0
2013-02-24   34   -2       0     0
2013-02-25   41   23       0     0
2013-02-26   40   21       0     0
2013-02-27   35   28      14     3
2013-02-28   33   28       0     0

[7139 rows x 4 columns]

In [8]:
df3 = pd.read_table('../combined/shtmax03.txt', sep='\s+',header=None,index_col=0)
maxS3 = df3.stack()
datesMax3=[]
for y in range(1893,2014):
    for d in range(1,32):
        time = "3"+"-"+str(d)+"-"+str(y)
        datesMax3.append(time)
dateMax3 = pd.Series(pd.to_datetime(date) for date in datesMax3)
#dateMax3
        
df3 = pd.DataFrame(data=maxS3.values,index=dateMax3)
df3.columns = ['Max']
#df3
dfMin3 = pd.read_table('../combined/shtmin03.txt', sep='\s+',header=None,index_col=0)
minS3 = dfMin3.stack()
dfPre3 = pd.read_table('../combined/shtpre03.txt', sep='\s+',header=None,index_col=0)
precipS3 = dfPre3.stack()
dfSno3 = pd.read_table('../combined/shtsno_b03.txt', sep='\s+',header=None,index_col=0)
snowS3 = dfSno3.stack()
df3['Min']=minS3.values
df3['Precip']=precipS3.values
df3['Snow']=snowS3.values
#df3

In [9]:
result2 = result1.combine_first(df3)
#result2.head(67)
#result2.tail(67)
#result2

In [10]:
df4 = pd.read_table('../combined/shtmax04.txt', sep='\s+',header=None,index_col=0)
maxS4 = df4.stack()
#print(maxS4.values)
datesMax4=[]
for y in range(1893,2013):
    for d in range(1,31):
        time = "4"+"-"+str(d)+"-"+str(y)
        datesMax4.append(time)
dateMax4 = pd.Series(pd.to_datetime(date) for date in datesMax4)
#dateMax4
        
df4 = pd.DataFrame(data=maxS4.values,index=dateMax4)
df4.columns = ['Max']
#df4



dfMin4 = pd.read_table('../combined/shtmin04.txt', sep='\s+',header=None,index_col=0)
minS4 = dfMin4.stack()
dfPre4 = pd.read_table('../combined/shtpre04.txt', sep='\s+',header=None,index_col=0)
precipS4 = dfPre4.stack()
dfSno4 = pd.read_table('../combined/shtsno_b04.txt', sep='\s+',header=None,index_col=0)
snowS4 = dfSno4.stack()
df4['Min']=minS4.values
df4['Precip']=precipS4.values
df4['Snow']=snowS4.values
df4

            Max  Min  Precip  Snow
1893-04-01  -99  -99   -9900     0
1893-04-02  -99  -99   -9900     0
1893-04-03  -99  -99   -9900     0
1893-04-04  -99  -99   -9900     0
1893-04-05  -99  -99   -9900     0
1893-04-06  -99  -99   -9900     0
1893-04-07  -99  -99   -9900     0
1893-04-08  -99  -99   -9900     0
1893-04-09  -99  -99   -9900     0
1893-04-10  -99  -99   -9900     0
1893-04-11  -99  -99   -9900     0
1893-04-12  -99  -99   -9900     0
1893-04-13  -99  -99   -9900     0
1893-04-14  -99  -99   -9900     0
1893-04-15  -99  -99   -9900     0
1893-04-16  -99  -99   -9900     0
1893-04-17  -99  -99   -9900     0
1893-04-18  -99  -99   -9900     0
1893-04-19  -99  -99   -9900     0
1893-04-20  -99  -99   -9900     0
1893-04-21  -99  -99   -9900     0
1893-04-22  -99  -99   -9900     0
1893-04-23  -99  -99   -9900     0
1893-04-24  -99  -99   -9900     0
1893-04-25  -99  -99   -9900     0
1893-04-26  -99  -99   -9900     0
1893-04-27  -99  -99   -9900     0
1893-04-28  -99  -99   -9900     0
1893-04-29  -99  -99   -9900     0
1893-04-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2012-04-01   66   37       0     0
2012-04-02   68   47       0     0
2012-04-03   67   48       0     0
2012-04-04   63   37       0     0
2012-04-05   63   38       0     0
2012-04-06   59   28       0     0
2012-04-07   60   38       1     0
2012-04-08   65   28       1     0
2012-04-09   61   27       0     0
2012-04-10   53   23       0     0
2012-04-11   53   26       0     0
2012-04-12   62   25       0     0
2012-04-13   62   46       5     0
2012-04-14   72   48       4     0
2012-04-15   75   58     176     0
2012-04-16   75   39       4     0
2012-04-17   61   28       0     0
2012-04-18   68   51       8     0
2012-04-19   66   42      96     0
2012-04-20   54   36      93     0
2012-04-21   56   29       0     0
2012-04-22   58   42       6     0
2012-04-23   62   35       0     0
2012-04-24   70   41       0     0
2012-04-25   72   49       1     0
2012-04-26   69   46       0     0
2012-04-27   57   36       0     0
2012-04-28   51   38      30     0
2012-04-29   55   39       0     0
2012-04-30   55   42      77     0

[3600 rows x 4 columns]

In [11]:
result3 = result2.combine_first(df4)
#result3.head(100)
result3

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[14490 rows x 4 columns]

In [35]:
df5 = pd.read_table('../combined/shtmax05.txt', sep='\s+',header=None,index_col=0)
maxS5 = df5.stack()
#print(maxS4.values)
datesMax5=[]
for y in range(1893,2013):
    for d in range(1,32):
        time = "5"+"-"+str(d)+"-"+str(y)
        datesMax5.append(time)
dateMax5 = pd.Series(pd.to_datetime(date) for date in datesMax5)
dateMax5
        
df5 = pd.DataFrame(data=maxS5.values,index=dateMax5)
df5.columns = ['Max']
#df5



dfMin5 = pd.read_table('../combined/shtmin05.txt', sep='\s+',header=None,index_col=0)
minS5 = dfMin5.stack()
dfPre5 = pd.read_table('../combined/shtpre05.txt', sep='\s+',header=None,index_col=0)
precipS5 = dfPre5.stack()
dfSno5 = pd.read_table('../combined/shtsno_b05.txt', sep='\s+',header=None,index_col=0)
snowS5 = dfSno5.stack()
df5['Min']=minS5.values
df5['Precip']=precipS5.values
df5['Snow']=snowS5.values
#df5.head(50)
df

            Max  Min  Precip  Snow
1893-03-01   26    4       0     0
1893-03-02   20    9       0     0
1893-03-03   10    0       0     0
1893-03-04   18   -9       0     0
1893-03-05   29  -10       0     0
1893-03-06   23   -9       0     0
1893-03-07   46   15      70     5
1893-03-08   40   23       0     0
1893-03-09   43   20       0     0
1893-03-10   50   29      40     3
1893-03-11   40   30       0     0
1893-03-12   41   29       0     0
1893-03-13   37   12       0     0
1893-03-14   41    5       0     0
1893-03-15   22    7       0     0
1893-03-16   24   12       0     0
1893-03-17   35    8       0     0
1893-03-18   36   10       0     0
1893-03-19   37   29       0     0
1893-03-20   44   33       0     0
1893-03-21   41   34       0     0
1893-03-22   47   23      90     6
1893-03-23   53   31       0     0
1893-03-24   35   22       0     0
1893-03-25   41   19       0     0
1893-03-26   39   24       0     0
1893-03-27   41   22       0     0
1893-03-28   47   27       0     0
1893-03-29   54   33       0     0
1893-03-30   56   39       0     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[43442 rows x 4 columns]

In [13]:
result4 = result3.combine_first(df5)
#result4.tail(302)
result4

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[18210 rows x 4 columns]

In [14]:
df6 = pd.read_table('../combined/shtmax06.txt', sep='\s+',header=None,index_col=0)
maxS6 = df6.stack()
#print(maxS6.values)
datesMax6=[]
for y in range(1893,2013):
    for d in range(1,31):
        time = "6"+"-"+str(d)+"-"+str(y)
        datesMax6.append(time)
dateMax6 = pd.Series(pd.to_datetime(date) for date in datesMax6)
#dateMax6
        
df6 = pd.DataFrame(data=maxS6.values,index=dateMax6)
df6.columns = ['Max']
#df6



dfMin6 = pd.read_table('../combined/shtmin06.txt', sep='\s+',header=None,index_col=0)
minS6 = dfMin6.stack()
dfPre6 = pd.read_table('../combined/shtpre06.txt', sep='\s+',header=None,index_col=0)
precipS6 = dfPre6.stack()
dfSno6 = pd.read_table('../combined/shtsno_b06.txt', sep='\s+',header=None,index_col=0)
snowS6 = dfSno6.stack()
df6['Min']=minS6.values
df6['Precip']=precipS6.values
df6['Snow']=snowS6.values
df6

            Max  Min  Precip  Snow
1893-06-01  -99  -99   -9900     0
1893-06-02  -99  -99   -9900     0
1893-06-03  -99  -99   -9900     0
1893-06-04  -99  -99   -9900     0
1893-06-05  -99  -99   -9900     0
1893-06-06  -99  -99   -9900     0
1893-06-07  -99  -99   -9900     0
1893-06-08  -99  -99   -9900     0
1893-06-09  -99  -99   -9900     0
1893-06-10  -99  -99   -9900     0
1893-06-11  -99  -99   -9900     0
1893-06-12  -99  -99   -9900     0
1893-06-13  -99  -99   -9900     0
1893-06-14  -99  -99   -9900     0
1893-06-15  -99  -99   -9900     0
1893-06-16  -99  -99   -9900     0
1893-06-17  -99  -99   -9900     0
1893-06-18   88   55       0     0
1893-06-19   91   68       0     0
1893-06-20   90   65       0     0
1893-06-21   86   65      87     0
1893-06-22   79   52       0     0
1893-06-23   80   53       0     0
1893-06-24   81   63      25     0
1893-06-25   79   57       0     0
1893-06-26   80   53       0     0
1893-06-27   82   56       0     0
1893-06-28   85   54       0     0
1893-06-29   86   59       0     0
1893-06-30   81   63       0     0
...         ...  ...     ...   ...
2012-06-01   68   41       0     0
2012-06-02   73   42       0     0
2012-06-03   79   45       1     0
2012-06-04   81   57      11     0
2012-06-05   81   55       0     0
2012-06-06   79   52       0     0
2012-06-07   82   51       0     0
2012-06-08   86   58       0     0
2012-06-09   89   62       0     0
2012-06-10   89   67       0     0
2012-06-11   89   65      32     0
2012-06-12   81   51       0     0
2012-06-13   74   46       0     0
2012-06-14   85   59       0     0
2012-06-15   86   61      27     0
2012-06-16   87   67       0     0
2012-06-17   85   56       8     0
2012-06-18   92   75       0     0
2012-06-19   93   77       0     0
2012-06-20   91   75       0     0
2012-06-21   89   59      79     0
2012-06-22   83   54       0     0
2012-06-23   83   59       0     0
2012-06-24   85   59       0     0
2012-06-25   85   65       0     0
2012-06-26   82   49       0     0
2012-06-27   95   66       0     0
2012-06-28   95   73       0     0
2012-06-29   92   57       0     0
2012-06-30   93   62       0     0

[3600 rows x 4 columns]

In [15]:
result5 = result4.combine_first(df6)
#result5.tail(302)
result5

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[21810 rows x 4 columns]

In [16]:
df7 = pd.read_table('../combined/shtmax07.txt', sep='\s+',header=None,index_col=0)
maxS7 = df7.stack()
#print(maxS7.values)
datesMax7=[]
for y in range(1893,2013):
    for d in range(1,32):
        time = "7"+"-"+str(d)+"-"+str(y)
        datesMax7.append(time)
dateMax7 = pd.Series(pd.to_datetime(date) for date in datesMax7)
#dateMax6
        
df7 = pd.DataFrame(data=maxS7.values,index=dateMax7)
df7.columns = ['Max']
#df7


dfMin7 = pd.read_table('../combined/shtmin07.txt', sep='\s+',header=None,index_col=0)
minS7 = dfMin7.stack()
dfPre7 = pd.read_table('../combined/shtpre07.txt', sep='\s+',header=None,index_col=0)
precipS7 = dfPre7.stack()
dfSno7 = pd.read_table('../combined/shtsno_b07.txt', sep='\s+',header=None,index_col=0)
snowS7 = dfSno7.stack()
df7['Min']=minS7.values
df7['Precip']=precipS7.values
df7['Snow']=snowS7.values
df7

            Max  Min  Precip  Snow
1893-07-01  -99  -99   -9900     0
1893-07-02  -99  -99   -9900     0
1893-07-03  -99  -99   -9900     0
1893-07-04  -99  -99   -9900     0
1893-07-05  -99  -99   -9900     0
1893-07-06  -99  -99   -9900     0
1893-07-07  -99  -99   -9900     0
1893-07-08  -99  -99   -9900     0
1893-07-09  -99  -99   -9900     0
1893-07-10  -99  -99   -9900     0
1893-07-11  -99  -99   -9900     0
1893-07-12  -99  -99   -9900     0
1893-07-13  -99  -99   -9900     0
1893-07-14  -99  -99   -9900     0
1893-07-15  -99  -99   -9900     0
1893-07-16  -99  -99   -9900     0
1893-07-17  -99  -99   -9900     0
1893-07-18  -99  -99   -9900     0
1893-07-19  -99  -99   -9900     0
1893-07-20  -99  -99   -9900     0
1893-07-21  -99  -99   -9900     0
1893-07-22  -99  -99   -9900     0
1893-07-23  -99  -99   -9900     0
1893-07-24  -99  -99   -9900     0
1893-07-25  -99  -99   -9900     0
1893-07-26  -99  -99   -9900     0
1893-07-27  -99  -99   -9900     0
1893-07-28  -99  -99   -9900     0
1893-07-29  -99  -99   -9900     0
1893-07-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2012-07-02   97   71       0     0
2012-07-03   98   72       0     0
2012-07-04   99   74       0     0
2012-07-05   99   72       0     0
2012-07-06  101   72       0     0
2012-07-07  101   73       0     0
2012-07-08   87   66       0     0
2012-07-09   89   60       0     0
2012-07-10   88   58       0     0
2012-07-11   89   56       0     0
2012-07-12   90   56       0     0
2012-07-13   91   65      23     0
2012-07-14   86   66       5     0
2012-07-15   93   62       0     0
2012-07-16   97   65       0     0
2012-07-17  100   68       0     0
2012-07-18   98   70       1     0
2012-07-19   86   67      97     0
2012-07-20   85   57       0     0
2012-07-21   87   64       3     0
2012-07-22   91   68      15     0
2012-07-23   89   68       0     0
2012-07-24   87   70       0     0
2012-07-25  100   73       0     0
2012-07-26   98   69       2     0
2012-07-27   87   61       0     0
2012-07-28   83   58       0     0
2012-07-29   84   64       9     0
2012-07-30   94   63       0     0
2012-07-31   95   62       0     0

[3720 rows x 4 columns]

In [17]:
result6 = result5.combine_first(df7)
result6.tail(150)
#result6

            Max  Min  Precip  Snow
2012-06-02   73   42       0     0
2012-06-03   79   45       1     0
2012-06-04   81   57      11     0
2012-06-05   81   55       0     0
2012-06-06   79   52       0     0
2012-06-07   82   51       0     0
2012-06-08   86   58       0     0
2012-06-09   89   62       0     0
2012-06-10   89   67       0     0
2012-06-11   89   65      32     0
2012-06-12   81   51       0     0
2012-06-13   74   46       0     0
2012-06-14   85   59       0     0
2012-06-15   86   61      27     0
2012-06-16   87   67       0     0
2012-06-17   85   56       8     0
2012-06-18   92   75       0     0
2012-06-19   93   77       0     0
2012-06-20   91   75       0     0
2012-06-21   89   59      79     0
2012-06-22   83   54       0     0
2012-06-23   83   59       0     0
2012-06-24   85   59       0     0
2012-06-25   85   65       0     0
2012-06-26   82   49       0     0
2012-06-27   95   66       0     0
2012-06-28   95   73       0     0
2012-06-29   92   57       0     0
2012-06-30   93   62       0     0
2012-07-01   94   64       0     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[150 rows x 4 columns]

In [18]:
df8 = pd.read_table('../combined/shtmax08.txt', sep='\s+',header=None,index_col=0)
maxS8 = df8.stack()
#print(maxS8.values)
datesMax8=[]
for y in range(1893,2013):
    for d in range(1,32):
        time = "8"+"-"+str(d)+"-"+str(y)
        datesMax8.append(time)
dateMax8 = pd.Series(pd.to_datetime(date) for date in datesMax8)
#dateMax8
        
df8 = pd.DataFrame(data=maxS8.values,index=dateMax8)
df8.columns = ['Max']
#df8
dfMin8 = pd.read_table('../combined/shtmin08.txt', sep='\s+',header=None,index_col=0)
minS8 = dfMin8.stack()
dfPre8 = pd.read_table('../combined/shtpre08.txt', sep='\s+',header=None,index_col=0)
precipS8 = dfPre8.stack()
dfSno8 = pd.read_table('../combined/shtsno_b08.txt', sep='\s+',header=None,index_col=0)
snowS8 = dfSno8.stack()
df8['Min']=minS8.values
df8['Precip']=precipS8.values
df8['Snow']=snowS8.values
df8

            Max  Min  Precip  Snow
1893-08-01   83   53       0     0
1893-08-02   85   55       0     0
1893-08-03   87   58       0     0
1893-08-04   89   64       0     0
1893-08-05   86   59       0     0
1893-08-06   79   48       0     0
1893-08-07   82   56       0     0
1893-08-08   93   62       0     0
1893-08-09   93   62       0     0
1893-08-10   84   56      42     0
1893-08-11   72   46       0     0
1893-08-12   76   53       0     0
1893-08-13   76   51       0     0
1893-08-14   82   68       0     0
1893-08-15   81   65       0     0
1893-08-16   79   48       0     0
1893-08-17   85   55       0     0
1893-08-18   77   45       0     0
1893-08-19   80   52       0     0
1893-08-20   82   57       0     0
1893-08-21   81   62       6     0
1893-08-22   87   65       2     0
1893-08-23   88   65       0     0
1893-08-24   76   53       0     0
1893-08-25   65   47       0     0
1893-08-26   83   61       0     0
1893-08-27   76   49       0     0
1893-08-28   64   40       0     0
1893-08-29   74   38       0     0
1893-08-30   78   42       0     0
...         ...  ...     ...   ...
2012-08-02   95   69       6     0
2012-08-03   93   65       0     0
2012-08-04   93   67      64     0
2012-08-05   77   58       0     0
2012-08-06   86   48       0     0
2012-08-07   91   58       0     0
2012-08-08   91   59       0     0
2012-08-09   81   62      20     0
2012-08-10   76   55      25     0
2012-08-11   77   47       0     0
2012-08-12   77   56       7     0
2012-08-13   80   59      19     0
2012-08-14   82   54       0     0
2012-08-15   82   62       0     0
2012-08-16   79   66       3     0
2012-08-17   75   47       0     0
2012-08-18   75   43       0     0
2012-08-19   78   49      10     0
2012-08-20   78   44       0     0
2012-08-21   80   43       0     0
2012-08-22   84   47       0     0
2012-08-23   93   58       0     0
2012-08-24   91   64      37     0
2012-08-25   88   56       0     0
2012-08-26   83   67       7     0
2012-08-27   88   55       0     0
2012-08-28   88   57       0     0
2012-08-29   92   64       0     0
2012-08-30   95   73       0     0
2012-08-31   94   62       0     0

[3720 rows x 4 columns]

In [19]:
result7 = result6.combine_first(df8)
#result7.tail(100)
result7

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[29250 rows x 4 columns]

In [20]:
df9 = pd.read_table('../combined/shtmax09.txt', sep='\s+',header=None,index_col=0)
maxS9 = df9.stack()
#print(maxS9.values)
datesMax9=[]
for y in range(1893,2013):
    for d in range(1,31):
        time = "9"+"-"+str(d)+"-"+str(y)
        datesMax9.append(time)
dateMax9 = pd.Series(pd.to_datetime(date) for date in datesMax9)
#dateMax9
        
df9 = pd.DataFrame(data=maxS9.values,index=dateMax9)
df9.columns = ['Max']
#df9
dfMin9 = pd.read_table('../combined/shtmin09.txt', sep='\s+',header=None,index_col=0)
minS9 = dfMin9.stack()
dfPre9 = pd.read_table('../combined/shtpre09.txt', sep='\s+',header=None,index_col=0)
precipS9 = dfPre9.stack()
dfSno9 = pd.read_table('../combined/shtsno_b09.txt', sep='\s+',header=None,index_col=0)
snowS9 = dfSno9.stack()
df9['Min']=minS9.values
df9['Precip']=precipS9.values
df9['Snow']=snowS9.values
df9

            Max  Min  Precip  Snow
1893-09-01  -99  -99   -9900     0
1893-09-02  -99  -99   -9900     0
1893-09-03  -99  -99   -9900     0
1893-09-04  -99  -99   -9900     0
1893-09-05  -99  -99   -9900     0
1893-09-06  -99  -99   -9900     0
1893-09-07  -99  -99   -9900     0
1893-09-08  -99  -99   -9900     0
1893-09-09  -99  -99   -9900     0
1893-09-10  -99  -99   -9900     0
1893-09-11  -99  -99   -9900     0
1893-09-12  -99  -99   -9900     0
1893-09-13  -99  -99   -9900     0
1893-09-14  -99  -99   -9900     0
1893-09-15  -99  -99   -9900     0
1893-09-16  -99  -99   -9900     0
1893-09-17  -99  -99   -9900     0
1893-09-18  -99  -99   -9900     0
1893-09-19  -99  -99   -9900     0
1893-09-20  -99  -99   -9900     0
1893-09-21  -99  -99   -9900     0
1893-09-22  -99  -99   -9900     0
1893-09-23  -99  -99   -9900     0
1893-09-24  -99  -99   -9900     0
1893-09-25  -99  -99   -9900     0
1893-09-26  -99  -99   -9900     0
1893-09-27  -99  -99   -9900     0
1893-09-28  -99  -99   -9900     0
1893-09-29  -99  -99   -9900     0
1893-09-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2012-09-01   86   66       0     0
2012-09-02   88   58       0     0
2012-09-03   89   66      33     0
2012-09-04   94   61       4     0
2012-09-05   91   60     148     0
2012-09-06   81   49       0     0
2012-09-07   79   59       1     0
2012-09-08   76   45       0     0
2012-09-09   77   50       0     0
2012-09-10   76   44       0     0
2012-09-11   89   60       0     0
2012-09-12   88   60       0     0
2012-09-13   70   50      78     0
2012-09-14   75   46       0     0
2012-09-15   79   44       0     0
2012-09-16   78   47       0     0
2012-09-17   75   57       7     0
2012-09-18   61   38       0     0
2012-09-19   77   41       0     0
2012-09-20   77   39       0     0
2012-09-21   68   42      18     0
2012-09-22   62   37       5     0
2012-09-23   59   28       0     0
2012-09-24   75   28       0     0
2012-09-25   78   39       0     0
2012-09-26   78   34       0     0
2012-09-27   68   32       0     0
2012-09-28   73   33       0     0
2012-09-29   81   39       0     0
2012-09-30   81   37       0     0

[3600 rows x 4 columns]

In [21]:
result8 = result7.combine_first(df9)
#result8.tail(125)
result8

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[32850 rows x 4 columns]

In [22]:
df10 = pd.read_table('../combined/shtmax10.txt', sep='\s+',header=None,index_col=0)
maxS10 = df10.stack()
#print(maxS10.values)
datesMax10=[]
for y in range(1893,2013):
    for d in range(1,32):
        time = "10"+"-"+str(d)+"-"+str(y)
        datesMax10.append(time)
dateMax10 = pd.Series(pd.to_datetime(date) for date in datesMax10)
#dateMax10
        
df10 = pd.DataFrame(data=maxS10.values,index=dateMax10)
df10.columns = ['Max']
#df10
dfMin10 = pd.read_table('../combined/shtmin10.txt', sep='\s+',header=None,index_col=0)
minS10= dfMin10.stack()
dfPre10 = pd.read_table('../combined/shtpre10.txt', sep='\s+',header=None,index_col=0)
precipS10 = dfPre10.stack()
dfSno10 = pd.read_table('../combined/shtsno_b10.txt', sep='\s+',header=None,index_col=0)
snowS10 = dfSno10.stack()
df10['Min']=minS10.values
df10['Precip']=precipS10.values
df10['Snow']=snowS10.values
df10

            Max  Min  Precip  Snow
1893-10-01   69   51       0     0
1893-10-02   59   41       0     0
1893-10-03   59   40       0     0
1893-10-04   63   44       0     0
1893-10-05   70   49     130     0
1893-10-06   58   36      70     0
1893-10-07   69   44       0     0
1893-10-08   78   43       0     0
1893-10-09   74   56       0     0
1893-10-10   83   62       0     0
1893-10-11   79   46      50     0
1893-10-12   57   50       0     0
1893-10-13   59   41       0     0
1893-10-14   46   32       0     0
1893-10-15   62   34       0     0
1893-10-16   66   43       0     0
1893-10-17   68   42       0     0
1893-10-18   69   45       0     0
1893-10-19   56   42       0     0
1893-10-20   62   34       0     0
1893-10-21   75   54       0     0
1893-10-22   76   59       0     0
1893-10-23   80   28       0     0
1893-10-24   46   24       0     0
1893-10-25   51   37      15     0
1893-10-26   43   27       0     0
1893-10-27   57   23       8     0
1893-10-28   38   16       0     0
1893-10-29   38   14       0     0
1893-10-30   37   20       0     0
...         ...  ...     ...   ...
2012-10-02   73   46       0     0
2012-10-03   77   39       0     0
2012-10-04   77   49       0     0
2012-10-05   56   31       0     0
2012-10-06   49   32       0     0
2012-10-07   52   25       0     0
2012-10-08   66   32       0     0
2012-10-09   64   44      30     0
2012-10-10   52   28       0     0
2012-10-11   54   39       1     0
2012-10-12   52   23       0     0
2012-10-13   62   40      35     0
2012-10-14   65   47     104     0
2012-10-15   62   32       0     0
2012-10-16   68   43       0     0
2012-10-17   67   42       1     0
2012-10-18   59   43       6     0
2012-10-19   49   36      10     0
2012-10-20   54   28       0     0
2012-10-21   70   34       0     0
2012-10-22   70   48      37     0
2012-10-23   73   58       4     0
2012-10-24   73   62       1     0
2012-10-25   72   41      67     0
2012-10-26   43   28       0     0
2012-10-27   41   26       0     0
2012-10-28   48   20       0     0
2012-10-29   49   20       0     0
2012-10-30   50   22       0     0
2012-10-31   50   23       0     0

[3720 rows x 4 columns]

In [23]:
result9 = result8.combine_first(df10)
#result9.tail(130)
result9

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[36570 rows x 4 columns]

In [24]:
df11 = pd.read_table('../combined/shtmax11.txt', sep='\s+',header=None,index_col=0)
maxS11 = df11.stack()
#print(maxS11.values)
datesMax11=[]
for y in range(1893,2013):
    for d in range(1,31):
        time = "11"+"-"+str(d)+"-"+str(y)
        datesMax11.append(time)
dateMax11 = pd.Series(pd.to_datetime(date) for date in datesMax11)
#dateMax11
        
df11 = pd.DataFrame(data=maxS11.values,index=dateMax11)
df11.columns = ['Max']
#df11
dfMin11 = pd.read_table('../combined/shtmin11.txt', sep='\s+',header=None,index_col=0)
minS11 = dfMin11.stack()
dfPre11 = pd.read_table('../combined/shtpre11.txt', sep='\s+',header=None,index_col=0)
precipS11 = dfPre11.stack()
dfSno11 = pd.read_table('../combined/shtsno_b11.txt', sep='\s+',header=None,index_col=0)
snowS11 = dfSno11.stack()
df11['Min']=minS11.values
df11['Precip']=precipS11.values
df11['Snow']=snowS11.values
df11

            Max  Min  Precip  Snow
1893-11-01   72   33       0     0
1893-11-02   37   20       0     0
1893-11-03   49   18       0     0
1893-11-04   53   27       0     0
1893-11-05   65   26       0     0
1893-11-06   79   39       0     0
1893-11-07   63   29       0     0
1893-11-08   64   27       0     0
1893-11-09   64   29       0     0
1893-11-10   62   42       0     0
1893-11-11   61   32       0     0
1893-11-12   38   24       0     0
1893-11-13   42   18       0     0
1893-11-14   39   13       0     0
1893-11-15   30   26       0     0
1893-11-16   52   25       0     0
1893-11-17   47    8       0     0
1893-11-18   32   20       0     0
1893-11-19   32   18       0     0
1893-11-20   55   31       0     0
1893-11-21   36   21      40     4
1893-11-22   22    7       0     0
1893-11-23   12   -7       0     0
1893-11-24   12   -6       0     0
1893-11-25   32   10      90     8
1893-11-26   33   31       6     1
1893-11-27   35   21       0     0
1893-11-28   33   20       0     0
1893-11-29   22   10       0     0
1893-11-30   10  -13      15     2
...         ...  ...     ...   ...
2012-11-01   51   28       0     0
2012-11-02   48   20       0     0
2012-11-03   47   34       0     0
2012-11-04   47   35       3     0
2012-11-05   48   37       0     0
2012-11-06   46   27      19     0
2012-11-07   45   36       3     0
2012-11-08   54   32       0     0
2012-11-09   52   30       0     0
2012-11-10   73   47       2     0
2012-11-11   70   32      86     0
2012-11-12   32   21       0     0
2012-11-13   52   15       0     0
2012-11-14   53   30       0     0
2012-11-15   54   37       0     0
2012-11-16   53   21       0     0
2012-11-17   57   23       0     0
2012-11-18   57   35       0     0
2012-11-19   56   44      14     0
2012-11-20   58   33       0     0
2012-11-21   65   30       0     0
2012-11-22   63   49       0     0
2012-11-23   56   21       0     0
2012-11-24   30   16       0     0
2012-11-25   38   17       0     0
2012-11-26   38   19       0     0
2012-11-27   33    9       0     0
2012-11-28   40   13       0     0
2012-11-29   49   22       0     0
2012-11-30   47   29       0     0

[3600 rows x 4 columns]

In [25]:
result10 = result9.combine_first(df11)
#result10.tail(130)
result10

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[40170 rows x 4 columns]

In [26]:
df12 = pd.read_table('../combined/shtmax12.txt', sep='\s+',header=None,index_col=0)
maxS12 = df12.stack()
#print(maxS12.values)
datesMax12=[]
for y in range(1893,2013):
    for d in range(1,32):
        time = "12"+"-"+str(d)+"-"+str(y)
        datesMax12.append(time)
dateMax12 = pd.Series(pd.to_datetime(date) for date in datesMax12)
#dateMax12
        
df12 = pd.DataFrame(data=maxS12.values,index=dateMax12)
df12.columns = ['Max']
#df12
dfMin12 = pd.read_table('../combined/shtmin12.txt', sep='\s+',header=None,index_col=0)
minS12= dfMin12.stack()
dfPre12= pd.read_table('../combined/shtpre12.txt', sep='\s+',header=None,index_col=0)
precipS12 = dfPre12.stack()
dfSno12 = pd.read_table('../combined/shtsno_b12.txt', sep='\s+',header=None,index_col=0)
snowS12 = dfSno12.stack()
df12['Min']=minS12.values
df12['Precip']=precipS12.values
df12['Snow']=snowS12.values
df12

            Max  Min  Precip  Snow
1893-12-01    4   -8       0     0
1893-12-02   12   -1       2     1
1893-12-03   12   -7       0     0
1893-12-04   36   11       0     0
1893-12-05   23    1       0     0
1893-12-06   16    9       2     1
1893-12-07   29   14       0     0
1893-12-08   33   23       0     0
1893-12-09   36    3       2     1
1893-12-10   14    5      28     3
1893-12-11   20   -7       0     0
1893-12-12   -4  -13       0     0
1893-12-13   23  -12       0     0
1893-12-14   33   30      47     4
1893-12-15   33   12      21     3
1893-12-16   17   -2       0     0
1893-12-17   27   12       0     0
1893-12-18   35    3       0     0
1893-12-19   14   -3       0     0
1893-12-20   30   14       0     0
1893-12-21   41   25       0     0
1893-12-22   44   23       0     0
1893-12-23   50   34       8     2
1893-12-24   53   33      53     4
1893-12-25   33   22       3     1
1893-12-26   28   21       0     0
1893-12-27   37   29       6     2
1893-12-28   36   12       0     0
1893-12-29   18   11       0     0
1893-12-30   27   23       0     0
...         ...  ...     ...   ...
2012-12-02   51   31       1     0
2012-12-03   65   32       0     0
2012-12-04   61   25       0     0
2012-12-05   43   16       0     0
2012-12-06   46   33       0     0
2012-12-07   45   31       0     0
2012-12-08   39   19       0     0
2012-12-09   39   32      32     2
2012-12-10   32   17       0     0
2012-12-11   27    6       1     0
2012-12-12   45   18       0     0
2012-12-13   44   33       0     0
2012-12-14   46   19       0     0
2012-12-15   44   38      49     0
2012-12-16   42   30       2     0
2012-12-17   30   20       0     0
2012-12-18   31   21      11     1
2012-12-19   34   29       0     0
2012-12-20   33   26      38     5
2012-12-21   26   10       0     0
2012-12-22   32    1       0     0
2012-12-23   30    6       0     0
2012-12-24   23   10       1     0
2012-12-25   20    1       0     0
2012-12-26   22    2       0     0
2012-12-27   24   -2       0     0
2012-12-28   26   21       8     2
2012-12-29   24   11       2     1
2012-12-30   25   -2       0     0
2012-12-31   22   13       0     0

[3720 rows x 4 columns]

In [27]:
result11 = result10.combine_first(df12)
#result11.tail(100)
result11

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[43890 rows x 4 columns]

In [28]:
#Hottest/coldest day in record
df = result11.copy()
df

            Max  Min  Precip  Snow
1893-01-01  -99  -99   -9900     0
1893-01-02  -99  -99   -9900     0
1893-01-03  -99  -99   -9900     0
1893-01-04  -99  -99   -9900     0
1893-01-05  -99  -99   -9900     0
1893-01-06  -99  -99   -9900     0
1893-01-07  -99  -99   -9900     0
1893-01-08  -99  -99   -9900     0
1893-01-09  -99  -99   -9900     0
1893-01-10  -99  -99   -9900     0
1893-01-11  -99  -99   -9900     0
1893-01-12  -99  -99   -9900     0
1893-01-13  -99  -99   -9900     0
1893-01-14  -99  -99   -9900     0
1893-01-15  -99  -99   -9900     0
1893-01-16  -99  -99   -9900     0
1893-01-17  -99  -99   -9900     0
1893-01-18  -99  -99   -9900     0
1893-01-19  -99  -99   -9900     0
1893-01-20  -99  -99   -9900     0
1893-01-21  -99  -99   -9900     0
1893-01-22  -99  -99   -9900     0
1893-01-23  -99  -99   -9900     0
1893-01-24  -99  -99   -9900     0
1893-01-25  -99  -99   -9900     0
1893-01-26  -99  -99   -9900     0
1893-01-27  -99  -99   -9900     0
1893-01-28  -99  -99   -9900     0
1893-01-29  -99  -99   -9900     0
1893-01-30  -99  -99   -9900     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[43890 rows x 4 columns]

In [29]:
df = df[df.Min != -99] #deleting rows that had -99 as Min temperature
df

            Max  Min  Precip  Snow
1893-03-01   26    4       0     0
1893-03-02   20    9       0     0
1893-03-03   10    0       0     0
1893-03-04   18   -9       0     0
1893-03-05   29  -10       0     0
1893-03-06   23   -9       0     0
1893-03-07   46   15      70     5
1893-03-08   40   23       0     0
1893-03-09   43   20       0     0
1893-03-10   50   29      40     3
1893-03-11   40   30       0     0
1893-03-12   41   29       0     0
1893-03-13   37   12       0     0
1893-03-14   41    5       0     0
1893-03-15   22    7       0     0
1893-03-16   24   12       0     0
1893-03-17   35    8       0     0
1893-03-18   36   10       0     0
1893-03-19   37   29       0     0
1893-03-20   44   33       0     0
1893-03-21   41   34       0     0
1893-03-22   47   23      90     6
1893-03-23   53   31       0     0
1893-03-24   35   22       0     0
1893-03-25   41   19       0     0
1893-03-26   39   24       0     0
1893-03-27   41   22       0     0
1893-03-28   47   27       0     0
1893-03-29   54   33       0     0
1893-03-30   56   39       0     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[43442 rows x 4 columns]

In [30]:
#writing to a csv file
#df.to_csv('deacorahWeather.csv')

In [36]:
df = df.replace(-9900,0)
df

            Max  Min  Precip  Snow
1893-03-01   26    4       0     0
1893-03-02   20    9       0     0
1893-03-03   10    0       0     0
1893-03-04   18   -9       0     0
1893-03-05   29  -10       0     0
1893-03-06   23   -9       0     0
1893-03-07   46   15      70     5
1893-03-08   40   23       0     0
1893-03-09   43   20       0     0
1893-03-10   50   29      40     3
1893-03-11   40   30       0     0
1893-03-12   41   29       0     0
1893-03-13   37   12       0     0
1893-03-14   41    5       0     0
1893-03-15   22    7       0     0
1893-03-16   24   12       0     0
1893-03-17   35    8       0     0
1893-03-18   36   10       0     0
1893-03-19   37   29       0     0
1893-03-20   44   33       0     0
1893-03-21   41   34       0     0
1893-03-22   47   23      90     6
1893-03-23   53   31       0     0
1893-03-24   35   22       0     0
1893-03-25   41   19       0     0
1893-03-26   39   24       0     0
1893-03-27   41   22       0     0
1893-03-28   47   27       0     0
1893-03-29   54   33       0     0
1893-03-30   56   39       0     0
...         ...  ...     ...   ...
2013-03-02   29    1       0     0
2013-03-03   32    4       0     0
2013-03-04   32   23       3     0
2013-03-05   30   24      46     6
2013-03-06   30   20       0     0
2013-03-07   32   -4       0     0
2013-03-08   40   11       0     0
2013-03-09   39   31      21     0
2013-03-10   38   33      48     0
2013-03-11   36   29      70     3
2013-03-12   30   16       0     0
2013-03-13   30   15       0     0
2013-03-14   37   15       6     1
2013-03-15   39   22       0     0
2013-03-16   38   24       0     0
2013-03-17   32   15       0     0
2013-03-18   32   23      19     2
2013-03-19   25    9       0     0
2013-03-20   25    7       0     0
2013-03-21   26    1       0     0
2013-03-22   35    4       0     0
2013-03-23   37   15       0     0
2013-03-24   37   29       0     0
2013-03-25   35   23       0     0
2013-03-26   39   22       0     0
2013-03-27   41   18       0     0
2013-03-28   45   19       0     0
2013-03-29   52   23       0     0
2013-03-30   53   31       2     0
2013-03-31   49   27       2     0

[43442 rows x 4 columns]

In [37]:
#writing to a csv file
df.to_csv('deacorahWeather.csv')